# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Site settings
title: Unorz
email: vjudge404@gmail.com
description: Doubleplusorz...
footnote: > # this means to ignore newlines until "baseurl:"
  <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> by vjudge1
brand: >
  <i class="fa fa-github-alt"></i> Unorz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vjudge1.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html
timezone: Asia/Shanghai
paginate: 5
excerpt_separator: "\n\n\n\n"

disqus_shortname: vjudge1

twitter_username: vjudge404
facebook_username: vjudge404
github_username: vjudge1
#qqqun_name: "QQ 群"
#qqqun_idkey:
#weibo_username:
#qq:
#weibo_userid:

host: 0.0.0.0

# force https
force_https: vjudge1.github.io

statistics: '//s95.cnzz.com/z_stat.php?id=1256463916&web_id=1256463916'

# Gems
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate

# Build settings
markdown: kramdown

# Header icons (Font Awesome)
header_icons:
-
  name: 关于
  url: /about/
  icon: graduation-cap
-
  name: 源代码
  url: https://github.com/vjudge1/vjudge1.github.io
  icon: code
-
  name: RSS
  url: /feed.xml
  icon: rss

# External links
external_links:
-
  name: UPC Linux
  url: https://upclinux.github.io
-
  name: UPC Linux / Intro
  url: https://upclinux.github.io/intro/
-
  name: 环宇的博客
  url: http://www.lihuanyu.com
-
  name: 微尘风景BBS
  url: http://wangchenyu.net.cn
-
  name: Jerry Yuan
  url: http://jerry.weighingproduct.com

# Footer List
footer_links:
-
  name: 关于
  url: /about/
-
  name: 让我帮你百度一下
  url: https://vjudge1.github.io/kuso/sos/
-
  name: wikitrans
  url: https://wikitrans-1245.appspot.com/

